In [ ]:
#Взять датасет из домашнего задания №2. Проверить гипотезу о том, 
#в каком варианте теста (control/personalization) больше конверсия (converted) 
#и значимо ли это отличие статистически
import pandas as pd
import scipy.stats as stats
from scipy.optimize import Bounds
from scipy.optimize import minimize
import numpy as np

df_1 = pd.read_csv('marketing_campaign.csv')
df_2 = pd.read_csv('subscribers.csv')
df_3 = pd.read_csv('users.csv')
df_12 = df_1.merge(df_2, left_on = ['user_id'],
                    right_on =['user_id'], how = 'left')
df = df_12.merge(df_3, left_on = ['user_id'],
                    right_on =['user_id'], how = 'left')
df.head()

,user_id,date_served,marketing_channel,variant,language_displayed,converted,subscribing_channel,date_subscribed,date_canceled,is_retained,age_group,language_preferred
0,a1000,1/1/18,House Ads,personalization,English,True,House Ads,1/1/18,NaN,True,0-18 years,English
1,a1001,1/1/18,House Ads,personalization,English,True,House Ads,1/1/18,NaN,True,19-24 years,English
2,a1002,1/1/18,House Ads,personalization,English,True,House Ads,1/1/18,NaN,True,24-30 years,English
3,a1003,1/1/18,House Ads,personalization,English,True,House Ads,1/1/18,NaN,True,30-36 years,English
4,a1004,1/1/18,House Ads,personalization,English,True,House Ads,1/1/18,NaN,True,36-45 years,English

In [ ]:
dfp = pd.pivot_table(df, index = "variant", columns = "converted", values = "user_id", aggfunc = "count")
dfp.head()

converted        False  True
variant
control           4705    371
personalization   4241    705

H0: разницы в конверсии нет

H1: (вариант B) дает большую конверсию

In [ ]:
result = stats.chi2_contingency(dfp, correction = False)
chisq, pvalue = result[:2]

print(f"{chisq=}, {pvalue=}")

chisq=126.07767827548582, pvalue=2.9568009705199523e-29

In [1]:
#Цех может производить стулья и столы. На производство стула идет 5 единиц материала, на производство стола - 20 
#единиц (футов красного дерева). Стул требует 10 человеко-часов, стол - 15. 
#Имеется 400 единиц материала и 450 человеко-часов. Прибыль при производстве стула - 45 долларов США, 
#при производстве стола - 80 долларов США. Сколько надо сделать стульев и столов, чтобы получить 
#максимальную прибыль?

def value(x):
    return - 45*x[0] - 80*x[1]

In [ ]:
neq_cons = {'type': 'ineq',
            'fun': lambda x: np.array ([400 - 5  * x [0] - 20 * x [1], 
                                        450 - 10  * x [0] - 15 * x [1]])
}

In [ ]:
bnds = Bounds([0, 0], [np.inf, np.inf])

In [ ]:
x0 = np.array([10, 10])
res = minimize(value, x0, method='SLSQP', constraints=neq_cons, bounds=bnds)
print(res.x)

[24. 14.]

In [ ]:
print('Материалы:', 24 * 5 + 14 * 20, 'ед.')
print('Время:', 24 * 10 + 14 * 15, 'чел.*час')
print('Максимизированная прибыль составит:', -1*value([24, 14]),'долларов')